"""update_value_type

Revision ID: 4b03a930cdde
Revises: ca08485f1b63
Create Date: 2026-03-31 01:51:44.226409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b03a930cdde'
down_revision: Union[str, Sequence[str], None] = 'ca08485f1b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'value',
                    existing_type=sa.FLOAT(),
                    type_=sa.Numeric(precision=7, scale=2),
                    postgresql_using='value::numeric',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
