"""update_value_precision

Revision ID: 790ef27039cc
Revises: 4b03a930cdde
Create Date: 2026-03-31 01:54:23.518156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790ef27039cc'
down_revision: Union[str, Sequence[str], None] = '4b03a930cdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'value',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
