"""create_vehicle_model

Revision ID: ca08485f1b63
Revises: 
Create Date: 2026-03-31 01:17:44.493323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca08485f1b63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('value', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('FLEX', 'GASOLINE', 'ALCOHOL', 'DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', name='transmissiontype'), nullable=False),
    sa.Column('tank_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_manufacturer'), 'vehicle', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_vehicle_model_name'), 'vehicle', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_model_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_manufacturer'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
